const trains = [
    {
        trainNumber: "145UP",
        trainName: "Sukkur Express",
        departure: "Karachi City",
        destination: "Jacobabad",
        status: "On Time",
        currentStationIndex: 3,
        route: [
            "Karachi City",
            "Karachi Cantt",
            "Landhi",
            "Hyderabad Junction",
            "Tando Adam",
            "Nawabshah",
            "Padidan",
            "Mehrabpur",
            "Khairpur",
            "Rohri Junction",
            "Sukkur",
            "Shikarpur",
            "Jacobabad"
        ]
    },

    {
        trainNumber: "47UP",
        trainName: "Rehman Baba Express",
        departure: "Karachi Cantt",
        destination: "Peshawar Cantt",
        status: "Delayed",
        currentStationIndex: 5,
        route: [
            "Karachi Cantt",
            "Landhi",
            "Hyderabad Junction",
            "Tando Adam",
            "Nawabshah",
            "Mehrabpur",
            "Rohri Junction",
            "Rahim Yar Khan",
            "Bahawalpur",
            "Multan Cantt",
            "Khanewal Junction",
            "Toba Tek Singh",
            "Faisalabad",
            "Sangla Hill",
            "Hafizabad",
            "Wazirabad Junction",
            "Lala Musa Junction",
            "Rawalpindi",
            "Attock City Junction",
            "Nowshera Junction",
            "Peshawar City",
            "Peshawar Cantt"
        ]
    },

    {
        trainNumber: "11UP",
        trainName: "Hazara Express",
        departure: "Karachi City",
        destination: "Havelian",
        status: "On Time",
        currentStationIndex: 7,
        route: [
            "Karachi City",
            "Karachi Cantt",
            "Landhi",
            "Kotri Junction",
            "Hyderabad Junction",
            "Tando Adam",
            "Nawabshah",
            "Mehrabpur",
            "Khairpur",
            "Rohri Junction",
            "Rahim Yar Khan",
            "Bahawalpur",
            "Multan Cantt",
            "Khanewal Junction",
            "Shorkot Cantt Junction",
            "Jhang Sadar",
            "Sargodha Junction",
            "Malakwal Junction",
            "Mandi Bahauddin",
            "Lala Musa Junction",
            "Jhelum",
            "Rawalpindi",
            "Taxila Cantt",
            "Haripur Hazara",
            "Havelian"
        ]
    },

    {
        trainNumber: "13UP",
        trainName: "Awam Express",
        departure: "Karachi Cantt",
        destination: "Peshawar Cantt",
        status: "On Time",
        currentStationIndex: 10,
        route: [
            "Karachi Cantt",
            "Landhi",
            "Kotri Junction",
            "Hyderabad Junction",
            "Tando Adam",
            "Nawabshah",
            "Mehrabpur",
            "Khairpur",
            "Rohri Junction",
            "Ghotki",
            "Rahim Yar Khan",
            "Bahawalpur",
            "Multan Cantt",
            "Khanewal Junction",
            "Sahiwal",
            "Lahore Junction",
            "Gujranwala",
            "Wazirabad Junction",
            "Gujrat",
            "Lala Musa Junction",
            "Jhelum",
            "Rawalpindi",
            "Taxila Junction",
            "Attock City Junction",
            "Nowshera Junction",
            "Peshawar City",
            "Peshawar Cantt"
        ]
    },

    {
        trainNumber: "9UP",
        trainName: "Allama Iqbal Express",
        departure: "Karachi Cantt",
        destination: "Sialkot Junction",
        status: "Delayed",
        currentStationIndex: 12,
        route: [
            "Karachi Cantt",
            "Landhi",
            "Kotri Junction",
            "Hyderabad Junction",
            "Tando Adam",
            "Nawabshah",
            "Mehrabpur",
            "Rohri Junction",
            "Ghotki",
            "Rahim Yar Khan",
            "Bahawalpur",
            "Khanewal Junction",
            "Sahiwal",
            "Okara",
            "Raiwind Junction",
            "Lahore Junction",
            "Shahdara Bagh Junction",
            "Narang",
            "Narowal Junction",
            "Pasrur",
            "Chawinda",
            "Sialkot Junction"
        ]
    },

    {
        trainNumber: "45UP",
        trainName: "Pakistan Express",
        departure: "Karachi Cantt",
        destination: "Rawalpindi",
        status: "On Time",
        currentStationIndex: 8,
        route: [
            "Karachi Cantt",
            "Landhi",
            "Hyderabad Junction",
            "Tando Adam",
            "Rohri Junction",
            "Sadiqabad",
            "Rahim Yar Khan",
            "Khanpur Junction",
            "Bahawalpur",
            "Multan Cantt",
            "Khanewal Junction",
            "Abdul Hakim",
            "Shorkot Cantt Junction",
            "Toba Tek Singh",
            "Gojra",
            "Faisalabad",
            "Sangla Hill Junction",
            "Hafizabad",
            "Wazirabad Junction",
            "Gujrat",
            "Lala Musa Junction",
            "Jhelum",
            "Gujar Khan",
            "Rawalpindi"
        ]
    },

    {
        trainNumber: "37UP",
        trainName: "Fareed Express",
        departure: "Karachi City",
        destination: "Lahore Junction",
        status: "On Time",
        currentStationIndex: 9,
        route: [
            "Karachi City",
            "Karachi Cantt",
            "Landhi",
            "Kotri Junction",
            "Hyderabad Junction",
            "Tando Adam",
            "Nawabshah",
            "Mehrabpur",
            "Rohri Junction",
            "Ghotki",
            "Rahim Yar Khan",
            "Khanpur Junction",
            "Bahawalpur",
            "Lodhran Junction",
            "Mailsi",
            "Vehari",
            "Burewala",
            "Arifwala",
            "Pakpattan",
            "Basirpur",
            "Kanganpur",
            "Kasur Junction",
            "Raiwind Junction",
            "Kot Lakhpat",
            "Lahore Junction"
        ]
    }
];
const train = trains[0];

console.log(train.route[train.currentStationIndex]);
// Hyderabad Junction